name: AHDY_FRONT_PROD # Workflow 이름
on:
    push:
        branches:
            - product
jobs: # Job 설정
    build:
    runs-on: ubuntu-latest
    steps:

        - uses: actions/checkout@v2
        - name: Run scripts in server
          uses: actions/checkout@product
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd server
            git reset --hard
            git fetch
            git pull

        - name: Cache node modules
          uses: actions/cache@v1
          with:
              path: node_modules
              key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                  ${{ runner.OS }}-build-
                  ${{ runner.OS }}-
        - name: Install Dependencies # 의존 파일 설치
          run: yarn install

        - name: Build # React Build
          run: yarn build
